"""
catalog_builder.py
------------------
Aggregates multiple AudioAnalysisRecord objects into a single
human-readable catalog file.

Catalog formats
---------------
  Markdown : one entry per file, sorted by category then filename
             → ideal for human review (open in any Markdown viewer)
  CSV      : flat table of all records
             → ideal for spreadsheet review or import into databases

The Markdown catalog is also designed to be useful for search:
each entry is a self-contained block with file name, description,
tags, and events — easy to grep or Ctrl+F through.
"""

from __future__ import annotations

import datetime
import logging
from pathlib import Path
from typing import List, Optional

from .schema import AudioAnalysisRecord
from .serializer import save_csv

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Markdown catalog
# ---------------------------------------------------------------------------

def build_catalog_markdown(
    records: List[AudioAnalysisRecord],
    output_path: str | Path,
    title: str = "Audio Catalog",
) -> Path:
    """
    Write a single Markdown file containing all records, sorted by category.

    Parameters
    ----------
    records     : list of analysis results
    output_path : where to write the .md file
    title       : document title

    Returns the path to the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Sort by category, then by filename
    sorted_records = sorted(records, key=lambda r: (r.primary_category, r.file_name))

    lines: List[str] = _catalog_header(title, len(records))

    # Group by category for better navigation
    current_category = None
    for r in sorted_records:
        if r.primary_category != current_category:
            current_category = r.primary_category
            lines.append(f"\n## {current_category.title()}\n")

        lines.extend(_record_catalog_block(r))
        lines.append("")  # blank line between entries

    lines.append(_catalog_footer())

    output_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Saved catalog Markdown (%d records): %s", len(records), output_path)
    return output_path


# ---------------------------------------------------------------------------
# CSV catalog (delegates to serializer.save_csv)
# ---------------------------------------------------------------------------

def build_catalog_csv(
    records: List[AudioAnalysisRecord],
    output_path: str | Path,
) -> Path:
    """
    Write a flat CSV catalog of all records.
    Delegates to serializer.save_csv for consistent column format.
    """
    return save_csv(records, output_path)


# ---------------------------------------------------------------------------
# Internal formatting helpers
# ---------------------------------------------------------------------------

def _catalog_header(title: str, count: int) -> List[str]:
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    return [
        f"# {title}",
        "",
        f"Generated: {now}  |  Total files: {count}",
        "",
        "---",
        "",
        "## Table of Contents",
        "",
        "_Files are grouped by primary sound category, then sorted alphabetically._",
        "",
        "---",
    ]


def _record_catalog_block(r: AudioAnalysisRecord) -> List[str]:
    """Format a single record as a compact catalog entry block."""
    tag_str = ", ".join(f"`{t}`" for t in r.tags[:6])
    event_str = " → ".join(r.sound_events[:5]) if r.sound_events else "—"
    conf_bar = _confidence_bar(r.confidence)

    return [
        f"### `{r.file_name}`",
        "",
        f"**{r.short_description}**",
        "",
        f"{r.detailed_description}",
        "",
        f"| | |",
        f"|---|---|",
        f"| **Duration** | {r.metadata.duration_seconds:.2f}s |",
        f"| **Label** | {r.primary_label} |",
        f"| **Confidence** | {conf_bar} {r.confidence:.2f} |",
        f"| **Events** | {event_str} |",
        f"| **Tags** | {tag_str} |",
        "",
        "---",
    ]


def _catalog_footer() -> str:
    return (
        "\n_This catalog was generated by the Audio Analyzer — Phase 1._\n"
        "_Descriptions are based on CLAP zero-shot classification + acoustic feature analysis._\n"
    )


def _confidence_bar(conf: float, width: int = 5) -> str:
    """Simple ASCII confidence bar: ████░ (filled/empty blocks)."""
    filled = round(conf * width)
    empty = width - filled
    return "█" * filled + "░" * empty
